{{{from}}}

WORKDIR /app

RUN python -m pip install --upgrade pip

RUN apt-get update && apt-get -y install git
RUN apt-get -y install cmake

RUN git clone https://github.com/eclipse-cyclonedds/cyclonedds
RUN mkdir cyclonedds/build 
RUN mkdir cyclonedds/install  
RUN cd cyclonedds/build && cmake .. -DCMAKE_INSTALL_PREFIX=../install
RUN cd cyclonedds/build && cmake --build . --target install
ENV CYCLONEDDS_HOME="/app/cyclonedds/install"
RUN pip3 install git+https://github.com/eclipse-cyclonedds/cyclonedds-python

{{{include}}}

COPY src src
COPY subscriber.py subscriber.py
COPY loop.py loop.py
COPY pub.py pub.py
COPY cyclonedds.xml cyclonedds.xml


ENV CYCLONEDDS_URI file:///app/cyclonedds.xml

COPY wrapper.sh wrapper.sh
RUN apt-get update && apt-get -y install dos2unix 
RUN dos2unix wrapper.sh
RUN chmod 0700 wrapper.sh
CMD ./wrapper.sh
#CMD python loop.py
